[platformio]
src_dir = Magicling_code
lib_dir = Magicling_code/libraries

[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
build_src_filter =
  +<*>
  -<libraries/>

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions_ota_2m.csv

build_flags =
  -DCORE_DEBUG_LEVEL=0
